# Site settings
title: "Marjan Ahmed: The Portofolio"
description: "Showcase of my projects, resume, and contact information."

theme: jekyll-theme-cayman

author: Mohammed Marjan Ahmed Mashud
url: "https://marjanahmed21.github.io/"

# Navigation links
navbar:
  - name: "Home"
    link: "/"
  - name: "About"
    link: "/about"
  - name: "Resume"
    link: "/resume"
  - name: "Contact"
    link: "/contact"

